const pages={home:'Today',school:'School',tasks:'Tasks',calendar:'Calendar',projects:'Projects',inbox:'Inbox',career:'Career Profile',experiences:'Experience Vault',resumes:'Resumes',opportunities:'Opportunities',applications:'Applications',search:'Search',settings:'Settings'};
const stores=['profile','experiences','resumes','opportunities','applications','classes','tasks','events','projects','notes','inbox','documents','settings'];
let dbp; const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const navGroups=[['WORKSPACE',['home','tasks','calendar','projects','inbox','search']],['SCHOOL',['school']],['CAREER',['career','experiences','resumes','opportunities','applications']]];
function icon(x){return {home:'◈',tasks:'✓',calendar:'□',projects:'▱',inbox:'↓',search:'⌕',school:'▣',career:'◎',experiences:'◆',resumes:'▤',opportunities:'↗',applications:'→'}[x]||'•'}
function nav(){let n='';for(const[g,items]of navGroups)n+=`<div class="section">${g}</div>`+items.map(x=>`<button data-page="${x}" onclick="show('${x}')">${icon(x)} ${pages[x]}</button>`).join('');$('#nav').innerHTML=n}
function openDB(){if(dbp)return dbp;dbp=new Promise((resolve,reject)=>{const r=indexedDB.open('personal-command-center',1);r.onupgradeneeded=()=>{const d=r.result;for(const s of stores)if(!d.objectStoreNames.contains(s))d.createObjectStore(s,{keyPath:'id',autoIncrement:s!=='profile'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbp}
async function all(store){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(store,'readonly').objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function get(store,id){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(store,'readonly').objectStore(store).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function put(store,obj){const d=await openDB();return new Promise((res,rej)=>{const tx=d.transaction(store,'readwrite');const r=tx.objectStore(store).put(obj);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function add(store,obj){const d=await openDB();return new Promise((res,rej)=>{const tx=d.transaction(store,'readwrite');const r=tx.objectStore(store).add(obj);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function delStore(store,id){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(store,'readwrite').objectStore(store).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function initData(){if(!(await get('profile',1)))await put('profile',{id:1,name:'',school:'',major:'',concentration:'',graduation_year:'',career_interests:'',preferred_locations:'',preferred_job_types:'',skills:'',updated_at:new Date().toISOString()})}
function show(p){if(!pages[p])p='home';location.hash=p;$('#pageTitle').textContent=pages[p];$('#eyebrow').textContent=p==='home'?'HOME':p.toUpperCase();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));({home,school,tasks,calendar,projects,inbox,career,experiences,resumes,opportunities,applications,search,settings}[p]||home)().catch(e=>toast(e.message))}
function dateLabel(x){return x?String(x).slice(0,10):'No date'}
function sorted(a,key='id'){return [...a].sort((x,y)=>String(x[key]??'').localeCompare(String(y[key]??'')))}
function list(a,title,sub){return a.length?`<div class="list">${a.map(x=>`<div class="row"><div><div class="row-title">${esc(title(x))}</div><div class="row-sub">${esc(sub(x))}</div></div></div>`).join('')}</div>`:'<div class="empty">Nothing here yet.</div>'}
async function dashboardData(){const [tasks0,events0,opps,apps,projects0,classes0]=await Promise.all(['tasks','events','opportunities','applications','projects','classes'].map(all));const today=new Date().toISOString().slice(0,10);const tasks=tasks0.filter(x=>x.status!=='DONE').sort((a,b)=>(a.due_date||'9999').localeCompare(b.due_date||'9999'));const events=events0.filter(x=>(x.start_at||'').slice(0,10)>=today).sort((a,b)=>(a.start_at||'').localeCompare(b.start_at||''));return {today,tasks,events,opportunities:opps.filter(x=>!['REJECTED','WITHDRAWN'].includes(x.status)).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'')),applications:apps.filter(x=>!['REJECTED','WITHDRAWN'].includes(x.status)).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'')),projects:projects0.filter(x=>x.status!=='DONE').sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'')),classes:classes0};}
async function home(){const d=await dashboardData();const due=d.tasks.filter(x=>x.due_date&&x.due_date<=d.today);$('#content').innerHTML=`<div class="hero"><div><div class="eyebrow">${new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</div><h2>What needs your attention?</h2><p class="muted">Your local command center. Works offline on this iPad.</p></div><button class="primary" onclick="quickAdd()">+ Add</button></div><div class="grid cols-4"><div class="card"><h3>Due / overdue</h3><div class="metric">${due.length}</div><span class="muted">open tasks</span></div><div class="card"><h3>Assignments</h3><div class="metric">${d.tasks.filter(x=>x.category==='assignment').length}</div><span class="muted">still open</span></div><div class="card"><h3>Applications</h3><div class="metric">${d.applications.length}</div><span class="muted">active</span></div><div class="card"><h3>Projects</h3><div class="metric">${d.projects.length}</div><span class="muted">active</span></div></div><div class="section-title"><h2>Today</h2></div><div class="two-col"><div class="card"><h3>Schedule</h3>${d.events.length?list(d.events.slice(0,8),x=>x.title,x=>`${x.start_at||''}${x.end_at?' → '+x.end_at:''}`):'<div class="empty">Nothing scheduled.</div>'}</div><div class="card"><h3>Do next</h3>${d.tasks.length?list(d.tasks.slice(0,8),x=>x.title,x=>`${x.due_date?'Due '+dateLabel(x.due_date):'No deadline'} · ${x.estimate_min||30} min · ${x.priority||'medium'}`):'<div class="empty">No open tasks.</div>'}</div></div><div class="section-title"><h2>Upcoming</h2></div><div class="grid cols-3"><div class="card"><h3>Applications</h3>${list(d.applications.slice(0,5),x=>`${x.company||'Company'} — ${x.title||'Role'}`,x=>x.deadline?'Due '+dateLabel(x.deadline):x.status)}</div><div class="card"><h3>Opportunities</h3>${list(d.opportunities.slice(0,5),x=>`${x.company||'Company'} — ${x.title||'Role'}`,x=>x.deadline?'Deadline '+dateLabel(x.deadline):x.status)}</div><div class="card"><h3>Projects</h3>${list(d.projects.slice(0,5),x=>x.name,x=>x.next_action||x.status)}</div></div>`}
async function school(){const [c,t]=await Promise.all([all('classes'),all('tasks')]);const assigns=t.filter(x=>x.category==='assignment');$('#content').innerHTML=`<div class="toolbar"><button class="primary" onclick="classForm()">+ Class</button><button class="primary" onclick="taskForm({category:'assignment'})">+ Assignment</button></div><div class="grid cols-2"><div class="card"><h3>Classes</h3>${c.map(x=>`<div class="row"><div><b>${esc((x.code||'')+' '+(x.name||''))}</b><div class="row-sub">${esc(x.professor||x.term||'')}</div></div><div class="actions"><button class="smallbtn" onclick='classForm(${JSON.stringify(x)})'>Edit</button><button class="smallbtn danger" onclick="del('classes',${x.id})">Delete</button></div></div>`).join('')||'<div class="empty">Add your first class.</div>'}</div><div class="card"><h3>Assignments</h3>${assigns.map(x=>`<div class="row"><div><b>${esc(x.title)}</b><div class="row-sub">${x.due_date?'Due '+dateLabel(x.due_date):'No due date'} · ${x.estimate_min||30} min</div></div><div class="actions"><button class="smallbtn" onclick='taskForm(${JSON.stringify(x)})'>Edit</button></div></div>`).join('')||'<div class="empty">Add an assignment.</div>'}</div></div>`}
async function tasks(){let t=await all('tasks');t.sort((a,b)=>(a.due_date||'9999').localeCompare(b.due_date||'9999'));$('#content').innerHTML=`<div class="toolbar"><button class="primary" onclick="taskForm()">+ Task</button><input id="taskFilter" class="search" placeholder="Filter tasks" oninput="filterRows(this.value,'taskrow')"></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Task</th><th>Due</th><th>Priority</th><th>Estimate</th><th>Status</th><th></th></tr></thead><tbody>${t.map(x=>`<tr class="taskrow"><td><b>${esc(x.title)}</b><br><span class="muted">${esc(x.description||'')}</span></td><td>${dateLabel(x.due_date)}</td><td>${esc(x.priority||'medium')}</td><td>${x.estimate_min||30}m</td><td><span class="pill ${x.status==='DONE'?'green':''}">${esc(x.status||'TODO')}</span></td><td><div class="actions"><button class="smallbtn" onclick='taskForm(${JSON.stringify(x)})'>Edit</button><button class="smallbtn danger" onclick="del('tasks',${x.id})">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No tasks yet.</td></tr>'}</tbody></table></div></div>`}
async function calendar(){let e=await all('events');e.sort((a,b)=>(a.start_at||'').localeCompare(b.start_at||''));$('#content').innerHTML=`<div class="toolbar"><button class="primary" onclick="eventForm()">+ Event</button><button class="smallbtn" onclick="importICS()">Import .ics</button></div><div class="card"><h3>Timeline</h3>${e.length?`<div class="timeline">${e.map(x=>`<div class="time">${esc((x.start_at||'').slice(11,16))}</div><div class="event"><b>${esc(x.title)}</b><div class="muted">${esc(x.start_at||'')} ${x.end_at?'→ '+esc(x.end_at):''}</div><div class="actions"><button class="smallbtn" onclick='eventForm(${JSON.stringify(x)})'>Edit</button><button class="smallbtn danger" onclick="del('events',${x.id})">Delete</button></div></div>`).join('')}</div>`:'<div class="empty">No events yet.</div>'}</div>`}
async function projects(){let p=await all('projects');$('#content').innerHTML=`<div class="toolbar"><button class="primary" onclick="projectForm()">+ Project</button></div><div class="grid cols-2">${p.map(x=>`<div class="card"><div class="split"><h3>${esc(x.name)}</h3><span class="pill">${esc(x.status||'ACTIVE')}</span></div><div class="muted">${esc(x.goal||'')}</div><p><b>Next action:</b> ${esc(x.next_action||'Not defined')}</p><p class="muted">${x.deadline?'Deadline '+dateLabel(x.deadline):'No deadline'} · ${x.last_activity?'Last activity '+dateLabel(x.last_activity):'No activity recorded'}</p><div class="actions"><button class="smallbtn" onclick='projectForm(${JSON.stringify(x)})'>Edit</button><button class="smallbtn danger" onclick="del('projects',${x.id})">Delete</button></div></div>`).join('')||'<div class="card empty">Create a project and define its next action.</div>'}</div>`}
async function inbox(){let a=await all('inbox');a.sort((x,y)=>String(y.created_at||'').localeCompare(String(x.created_at||'')));$('#content').innerHTML=`<div class="toolbar"><button class="primary" onclick="inboxForm()">+ Capture</button><button class="smallbtn" onclick="captureFile()">Attach file</button></div><div class="card"><div class="dropzone">Paste a job, syllabus, assignment, URL, note, screenshot text, or random idea. The original source stays here until you review it.</div><div class="list" style="margin-top:15px">${a.map(x=>`<div class="row"><div><div class="row-title">${esc(x.title||'Untitled')}</div><div class="row-sub">Suggested: ${esc(x.suggested_type||'review')} · ${esc(x.created_at||'')}</div></div><div class="actions"><span class="pill">${x.reviewed?'Reviewed':'Needs review'}</span><button class="smallbtn" onclick='inboxForm(${JSON.stringify(x)})'>Review</button><button class="smallbtn danger" onclick="del('inbox',${x.id})">Delete</button></div></div>`).join('')||'<div class="empty">Your inbox is empty.</div>'}</div></div>`}
async function career(){const p=await get('profile',1);$('#content').innerHTML=`<div class="card"><h3>Career profile</h3><form onsubmit="saveProfile(event)"><div class="form-grid">${fields(p,[['name','Name'],['school','School'],['major','Major'],['concentration','Concentration'],['graduation_year','Graduation year'],['preferred_locations','Preferred locations'],['preferred_job_types','Preferred job types'],['career_interests','Career interests','textarea',true],['skills','Skills / tools','textarea',true]])}</div><button class="primary">Save profile</button></form></div>`}
async function experiences(){let a=await all('experiences');$('#content').innerHTML=`<div class="toolbar"><button class="primary" onclick="experienceForm()">+ Experience</button></div><div class="grid cols-2">${a.map(x=>`<div class="card"><div class="split"><h3>${esc(x.position||'Experience')}</h3><span class="pill">${esc(x.type||'')}</span></div><b>${esc(x.organization||'')}</b><div class="muted">${dateLabel(x.start_date)} → ${dateLabel(x.end_date)}</div><p>${esc(x.responsibilities||'')}</p><p><b>Evidence / results:</b> ${esc(x.results||x.accomplishments||'')}</p><div class="actions"><button class="smallbtn" onclick='experienceForm(${JSON.stringify(x)})'>Edit</button><button class="smallbtn danger" onclick="del('experiences',${x.id})">Delete</button></div></div>`).join('')||'<div class="card empty">Your source-of-truth experience vault starts here.</div>'}</div>`}
async function resumes(){let a=await all('resumes');$('#content').innerHTML=`<div class="toolbar"><button class="primary" onclick="resumeForm()">+ Resume version</button></div><div class="grid cols-2">${a.map(x=>`<div class="card"><div class="split"><h3>${esc(x.name||'Resume')}</h3><span class="pill">${esc(x.kind||'master')} · v${x.version||1}</span></div><p class="muted">Updated ${esc(x.updated_at||x.created_at||'')}</p><pre class="resume-preview">${esc(x.content||'')}</pre><div class="actions"><button class="smallbtn" onclick='resumeForm(${JSON.stringify(x)})'>Edit</button><button class="smallbtn danger" onclick="del('resumes',${x.id})">Delete</button></div></div>`).join('')||'<div class="card empty">Add your master resume. It will never be overwritten by tailoring.</div>'}</div>`}
async function opportunities(){let a=await all('opportunities');a.sort((x,y)=>(x.deadline||'9999').localeCompare(y.deadline||'9999'));$('#content').innerHTML=`<div class="toolbar"><button class="primary" onclick="jobForm()">+ Import job</button><input class="search" placeholder="Filter opportunities" oninput="filterRows(this.value,'opprow')"></div><div class="grid cols-2">${a.map(x=>`<div class="card opprow"><div class="split"><div><h3>${esc(x.title||'Untitled role')}</h3><b>${esc(x.company||'')}</b></div><span class="pill">${esc(x.status||'DISCOVERED')}</span></div><p class="muted">${esc(x.location||'')} ${x.work_mode?'· '+esc(x.work_mode):''} ${x.pay?'· '+esc(x.pay):''}</p><p>${esc((x.description||'').slice(0,360))}${(x.description||'').length>360?'…':''}</p><p class="muted">${x.deadline?'Deadline '+dateLabel(x.deadline):'No deadline'} · ${esc(x.source||'manual')}</p><div class="actions"><button class="smallbtn" onclick='jobForm(${JSON.stringify(x)})'>Edit</button><button class="smallbtn" onclick="tailorFor(${x.id})">Analyze vs resume</button><button class="smallbtn danger" onclick="del('opportunities',${x.id})">Delete</button></div></div>`).join('')||'<div class="card empty">Import a job description or paste a listing.</div>'}</div>`}
async function applications(){let [a,o]=await Promise.all([all('applications'),all('opportunities')]);const map=Object.fromEntries(o.map(x=>[x.id,x]));$('#content').innerHTML=`<div class="toolbar"><button class="primary" onclick="applicationForm()">+ Application</button></div><div class="pipeline">${['DISCOVERED','INTERESTED','PREPARING','APPLIED','INTERVIEW','OFFER','REJECTED','WITHDRAWN'].map(s=>`<div class="card"><h3>${s}</h3>${a.filter(x=>x.status===s).map(x=>{let o=map[x.opportunity_id]||{};return `<div class="row"><div><b>${esc(o.company||'Unknown')}</b><div class="row-sub">${esc(o.title||'Role')} ${x.deadline?'· '+dateLabel(x.deadline):''}</div></div><button class="smallbtn" onclick='applicationForm(${JSON.stringify(x)})'>Edit</button></div>`}).join('')||'<div class="empty">None</div>'}</div>`).join('')}</div>`}
async function search(){ $('#content').innerHTML=`<div class="card"><h3>Search everything</h3><input id="globalSearch" class="search" autofocus placeholder="Try: marketing, Chargers, Excel, stakeholder theory…" oninput="doSearch(this.value)"><div id="results" class="list" style="margin-top:16px"></div></div>`}
async function doSearch(q){q=q.trim().toLowerCase();if(!q){$('#results').innerHTML='<div class="empty">Start typing to search your local data.</div>';return}let out=[];for(const s of stores){const rs=await all(s);for(const r of rs){const blob=JSON.stringify(r).toLowerCase();if(blob.includes(q))out.push({store:s,id:r.id,title:r.title||r.name||r.position||r.company||r.code||s,detail:(r.description||r.content||r.responsibilities||r.notes||'').slice(0,180)})}}$('#results').innerHTML=out.slice(0,80).map(x=>`<div class="row"><div><b>${esc(x.title)}</b><div class="row-sub">${esc(x.store)}${x.detail?' · '+esc(x.detail):''}</div></div><button class="smallbtn" onclick="openSearchResult('${x.store}',${x.id})">Open</button></div>`).join('')||'<div class="empty">No matches.</div>'}
function openSearchResult(store,id){const p={tasks:'tasks',classes:'school',experiences:'experiences',resumes:'resumes',opportunities:'opportunities',applications:'applications',projects:'projects',events:'calendar',inbox:'inbox',notes:'inbox'}[store]||'home';show(p)}
async function settings(){const rows=[['IndexedDB','Local database','FREE / LOCAL','Essential','Works offline; export JSON backup'],['PWA','Installable iPad app shell','FREE / LOCAL','Essential','Safari + Add to Home Screen'],['AI provider','Optional analysis/drafting','OFF by default','Optional','Manual workflows or local model can be added later'],['Job discovery','Public pages / user imports','No required service','Optional','Paste URL/description when web access is unavailable']];$('#content').innerHTML=`<div class="grid cols-2"><div class="card"><h3>iPad mode</h3><p>This version stores your data in this browser using IndexedDB. It does not need a server, account, API key, or subscription.</p><button class="primary" onclick="installHelp()">How to install on iPad</button><button class="smallbtn" onclick="exportBackup()">Export JSON backup</button><label class="filebtn">Restore JSON backup<input type="file" accept="application/json,.json" onchange="importBackup(this.files[0])"></label></div><div class="card"><h3>Zero-cost health check</h3><div class="table-wrap"><table class="table"><thead><tr><th>Dependency</th><th>Purpose</th><th>Cost</th><th>Essential</th><th>Fallback</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div><div class="card"><h3>Data ownership</h3><p class="muted">Export creates a portable JSON copy. Restore replaces matching records in your local browser database; review backups before restoring.</p><button class="smallbtn danger" onclick="resetDemo()">Clear all local data</button></div></div>`}
function fields(x,arr){return arr.map(([k,label,type='text',full=false])=>`<label class="${full?'full':''}">${label}${type==='textarea'?`<textarea name="${k}">${esc(x?.[k]||'')}</textarea>`:`<input type="${type}" name="${k}" value="${esc(x?.[k]||'')}">`}</label>`).join('')}
function form(title,html,onSubmit){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=`<form onsubmit="${onSubmit}(event)">${html}<div class="actions" style="justify-content:flex-end"><button type="button" class="smallbtn" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>`;$('#modal').classList.remove('hidden')}
function classForm(x={}){form(x.id?'Edit class':'Add class',`<div class="form-grid">${fields(x,[['code','Course code'],['name','Class name'],['professor','Professor'],['term','Term'],['notes','Notes','textarea',true]])}</div>`,`saveForm('classes',${x.id||0})`)}
function taskForm(x={}){form(x.id?'Edit task':'Add task',`<div class="form-grid">${fields(x,[['title','Title','text'],['due_date','Due date','date'],['priority','Priority'],['estimate_min','Estimate (minutes)','number'],['status','Status'],['category','Category'],['description','Description','textarea',true]])}</div>`,`saveForm('tasks',${x.id||0})`)}
function eventForm(x={}){form(x.id?'Edit event':'Add event',`<div class="form-grid">${fields(x,[['title','Title'],['start_at','Start (YYYY-MM-DD HH:MM)'],['end_at','End (YYYY-MM-DD HH:MM)'],['kind','Type'],['notes','Notes','textarea',true]])}</div>`,`saveForm('events',${x.id||0})`)}
function projectForm(x={}){form(x.id?'Edit project':'Add project',`<div class="form-grid">${fields(x,[['name','Name'],['goal','Goal','textarea',true],['deadline','Deadline','date'],['status','Status'],['next_action','Next action','textarea',true],['last_activity','Last activity','date'],['description','Description','textarea',true],['notes','Notes','textarea',true]])}</div>`,`saveForm('projects',${x.id||0})`)}
function experienceForm(x={}){form(x.id?'Edit experience':'Add experience',`<div class="form-grid">${fields(x,[['organization','Organization'],['position','Position'],['type','Type'],['start_date','Start','date'],['end_date','End','date'],['responsibilities','Responsibilities','textarea',true],['accomplishments','Accomplishments','textarea',true],['skills','Skills'],['tools','Tools/software'],['problems','Problems solved','textarea',true],['people','People/team'],['leadership','Leadership','textarea',true],['results','Results','textarea',true],['metrics','Legitimate metrics'],['stories','Stories','textarea',true],['notes','Notes','textarea',true]])}</div>`,`saveForm('experiences',${x.id||0})`)}
function resumeForm(x={}){form(x.id?'Edit resume':'Add resume',`<div class="form-grid">${fields(x,[['name','Name'],['kind','Kind'],['version','Version','number'],['content','Resume text','textarea',true]])}</div>`,`saveForm('resumes',${x.id||0})`)}
function jobForm(x={}){form(x.id?'Edit opportunity':'Import opportunity',`<div class="form-grid">${fields(x,[['company','Company'],['title','Job title'],['location','Location'],['work_mode','Work mode'],['pay','Pay'],['deadline','Deadline','date'],['posting_date','Posting date','date'],['url','URL'],['source','Source'],['status','Status'],['description','Job description','textarea',true],['responsibilities','Responsibilities','textarea',true],['required','Required qualifications','textarea',true],['preferred','Preferred qualifications','textarea',true]])}</div>`,`saveForm('opportunities',${x.id||0})`)}
function applicationForm(x={}){form(x.id?'Edit application':'Add application',`<div class="form-grid">${fields(x,[['opportunity_id','Opportunity ID','number'],['status','Status'],['deadline','Deadline','date'],['discovered_date','Discovered','date'],['applied_date','Applied','date'],['resume_id','Resume ID','number'],['recruiter','Recruiter/contact'],['interview_dates','Interview dates'],['followup_date','Follow-up','date'],['cover_letter','Cover letter notes','textarea',true],['questions','Application questions','textarea',true],['notes','Notes','textarea',true]])}</div>`,`saveForm('applications',${x.id||0})`)}
function inboxForm(x={}){form(x.id?'Review inbox item':'Capture to inbox',`<div class="form-grid">${fields(x,[['title','Title'],['suggested_type','Suggested type'],['source_url','URL'],['content','Original content','textarea',true],['reviewed','Reviewed (0/1)','number']])}</div>`,`saveForm('inbox',${x.id||0})`)}
async function saveForm(t,id,e){e.preventDefault();const d=Object.fromEntries(new FormData(e));if(id)d.id=id;d.updated_at=new Date().toISOString();if(!id)d.created_at=d.updated_at;try{if(id)await put(t,d);else await add(t,d);closeModal();toast('Saved');show(location.hash.slice(1)||'home')}catch(err){toast(err.message)}}
async function saveProfile(e){e.preventDefault();const d=Object.fromEntries(new FormData(e));d.id=1;d.updated_at=new Date().toISOString();await put('profile',d);toast('Profile saved')}
async function del(t,id){if(!confirm('Delete this item?'))return;await delStore(t,id);toast('Deleted');show(location.hash.slice(1)||'home')}
function closeModal(){ $('#modal').classList.add('hidden') }
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function filterRows(q,cls){document.querySelectorAll('.'+cls).forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q.toLowerCase())?'':'none')}
function quickAdd(){form('Quick add',`<label>Type<select name="type"><option value="task">Task</option><option value="assignment">Assignment</option><option value="event">Calendar event</option><option value="project">Project</option><option value="job">Job / internship</option><option value="note">Note</option></select></label><label>Title<input name="title" required autofocus></label><label>Date (optional)<input name="date" type="date"></label>`,'quickSave')}
async function quickSave(e){e.preventDefault();const d=Object.fromEntries(new FormData(e));const stamp=new Date().toISOString();let t,p;if(d.type==='event'){t='events';p={title:d.title,start_at:d.date||stamp.slice(0,16),created_at:stamp,updated_at:stamp}}else if(d.type==='job'){t='opportunities';p={title:d.title,discovered_date:d.date,source:'manual',status:'DISCOVERED',created_at:stamp,updated_at:stamp}}else if(d.type==='project'){t='projects';p={name:d.title,deadline:d.date,next_action:'',status:'ACTIVE',created_at:stamp,updated_at:stamp}}else if(d.type==='note'){t='notes';p={title:d.title,content:'',created_at:stamp,updated_at:stamp}}else{t='tasks';p={title:d.title,due_date:d.date,category:d.type==='assignment'?'assignment':'task',status:'TODO',priority:'medium',estimate_min:30,created_at:stamp,updated_at:stamp}}await add(t,p);closeModal();toast('Added');show(location.hash.slice(1)||'home')}
function openCommand(){let old=document.querySelector('.command');if(old){old.remove();document.querySelector('.command-overlay')?.remove();return}let ov=document.createElement('div');ov.className='command-overlay';ov.onclick=()=>{ov.remove();document.querySelector('.command')?.remove()};document.body.appendChild(ov);let c=document.createElement('div');c.className='command';c.innerHTML=`<input id="cmd" placeholder="Search or run a command…" autofocus><div class="command-list" id="cmdlist"></div>`;document.body.appendChild(c);$('#cmd').oninput=e=>renderCommands(e.target.value);renderCommands('')}
function renderCommands(q){const cmds=[['Go home','home'],['Add task','add-task'],['Add assignment','add-assignment'],['Import internship / job','add-job'],['Show applications','applications'],['Find anything','search'],['Show my resume','resumes'],['Start weekly review','weekly']].filter(x=>!q||x[0].toLowerCase().includes(q.toLowerCase()));$('#cmdlist').innerHTML=cmds.map(x=>`<button onclick="runCmd('${x[1]}')">${x[0]}</button>`).join('')||'<div class="empty">No command.</div>'}
function runCmd(x){document.querySelector('.command-overlay')?.click();if(x==='add-task')return taskForm();if(x==='add-assignment')return taskForm({category:'assignment'});if(x==='add-job')return jobForm();if(x==='search')return show('search');if(x==='weekly')return weeklyReview();show(x)}
async function tailorFor(id){const [r,o,ex]=await Promise.all([all('resumes'),get('opportunities',id),all('experiences')]);if(!r.length){toast('Add a master resume first');return}const master=r.find(x=>x.kind==='master')||r[0];const jd=[o.description,o.responsibilities,o.required,o.preferred].join(' ').toLowerCase();const words=[...new Set((jd.match(/[a-zA-Z][a-zA-Z+.#-]{2,}/g)||[]).map(x=>x.toLowerCase()))];const stop=new Set('the and with for from this that your will are you our job work team role years experience required preferred about have has into their they using use workable'.split(' '));const matches=ex.map(e=>{const blob=JSON.stringify(e).toLowerCase();return {e,hits:words.filter(w=>!stop.has(w)&&blob.includes(w)).length}}).filter(x=>x.hits).sort((a,b)=>b.hits-a.hits).slice(0,8);const resumeText=(master.content||'').toLowerCase();const gaps=words.filter(w=>!stop.has(w)&&!resumeText.includes(w)).slice(0,30);form('Resume change review',`<div class="notice"><b>Review first.</b> Nothing is written back to your master resume. Every suggested experience comes from your own vault.</div><h3>Job</h3><p>${esc(o.company||'')} — ${esc(o.title||'')}</p><h3>Relevant experience</h3>${matches.map(x=>`<div class="row"><div><b>${esc(x.e.position||'Experience')} — ${esc(x.e.organization||'')}</b><div class="row-sub">${x.hits} matching terms · ${esc(x.e.accomplishments||x.e.responsibilities||'')}</div></div></div>`).join('')||'<div class="empty">No direct matches found.</div>'}<h3 style="margin-top:16px">Keywords to investigate</h3><p class="muted">${esc(gaps.join(', ')||'None')}</p><h3>Master resume</h3><pre class="resume-preview">${esc(master.content||'')}</pre>`,'closeOnly')}
function closeOnly(e){e.preventDefault();closeModal()}
function installHelp(){alert('On iPad: open this app in Safari → Share → Add to Home Screen → Add. Once installed, it opens like an app. Keep the original web address bookmarked too for updates.')}
function importICS(){alert('Calendar import is supported in the next integration pass. For now, add events manually; the app is intentionally not dependent on a calendar service.')}
function captureFile(){const i=document.createElement('input');i.type='file';i.multiple=true;i.accept='.pdf,.doc,.docx,.txt,.png,.jpg,.jpeg';i.onchange=async()=>{for(const f of i.files){let text='';if(f.type.startsWith('text/'))text=await f.text();await add('inbox',{title:f.name,content:text,source_url:'',suggested_type:'document',reviewed:0,created_at:new Date().toISOString(),updated_at:new Date().toISOString(),file_name:f.name,file_type:f.type,file_size:f.size})}toast('File(s) captured to inbox');show('inbox')};i.click()}
async function exportBackup(){const payload={version:1,exported_at:new Date().toISOString(),data:{}};for(const s of stores)payload.data[s]=await all(s);const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='command-center-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Backup exported')}
async function importBackup(file){if(!file)return;try{const p=JSON.parse(await file.text());if(!p.data)throw Error('Invalid backup');for(const s of stores){for(const r of (p.data[s]||[]))await put(s,r)}toast('Backup restored');show('home')}catch(e){toast('Restore failed: '+e.message)}}
async function resetDemo(){if(!confirm('This clears all local Command Center data. Export a backup first if you need it.'))return;const d=await openDB();for(const s of stores.filter(x=>x!=='profile'))await new Promise((res,rej)=>{const r=d.transaction(s,'readwrite').objectStore(s).clear();r.onsuccess=res;r.onerror=()=>rej(r.error)});await put('profile',{id:1,updated_at:new Date().toISOString()});toast('Local data cleared');show('home')}
async function weeklyReview(){const d=await dashboardData();form('Weekly review',`<h3>Open tasks</h3>${list(d.tasks.slice(0,12),x=>x.title,x=>x.due_date?'Due '+dateLabel(x.due_date):'No deadline')}<h3 style="margin-top:18px">Applications</h3>${list(d.applications.slice(0,8),x=>x.title||'Application',x=>x.status||'')}<h3 style="margin-top:18px">Projects needing attention</h3>${list(d.projects.filter(x=>x.status!=='DONE').slice(0,8),x=>x.name,x=>x.next_action||'No next action')}`,'closeOnly')}
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if(e.key==='Escape'){document.querySelector('.command-overlay')?.click();closeModal()}});window.onhashchange=()=>show(location.hash.slice(1)||'home');(async()=>{try{await openDB();await initData();nav();show(location.hash.slice(1)||'home')}catch(e){document.body.innerHTML='<div style="padding:30px;font-family:system-ui"><h1>Command Center could not start</h1><p>'+esc(e.message)+'</p></div>'}})();
